[providers]
php = true

[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.build]
cmds = ["composer install --no-dev --no-interaction"]

[start]
cmd = "php -S 0.0.0.0:$PORT"
